-- Lovable generated this migration while applying
-- 20260825055102_add_intensive_conversion_tracking.sql. The schema change is
-- already represented by that earlier migration, so this history placeholder
-- intentionally performs no SQL on a clean database.
