-- Lovable generated this migration while applying
-- 20260825085412_correct_intensive_conversion_baseline.sql. The correction is
-- already represented by that earlier migration, so this history placeholder
-- intentionally performs no SQL on a clean database.
